#!/usr/bin/env python3
"""Generate the firmware's weather icon .c files from Meteocons SVG artwork.

Why this exists
---------------
src/img/*.c used to be hand-made conversions of a dated, black-outlined icon
set that disappeared against the dark theme (the weather panel background is a
greyscale ramp driven by g_ui_darkness). This script regenerates them from
Meteocons v3 - flat colour, legible on both light and dark backgrounds.

The generated files keep the EXACT symbol names and descriptor layout of the
files they replace, so main.cpp needs no changes at all.

Usage
-----
    tools/make-weather-icons.py                    # fill style, 68 px, into src/img
    tools/make-weather-icons.py --style line       # thin monochrome outline set
    tools/make-weather-icons.py --style monochrome # solid single-colour set
    tools/make-weather-icons.py --size 96          # bigger source (costs more flash)
    tools/make-weather-icons.py --dry-run          # report, write nothing

Requirements: rsvg-convert (librsvg) on PATH, network access for first download.
SVGs are cached under tools/.meteocons-cache/ so later runs work offline.

Output format
-------------
LVGL 9 ARGB8888, matching what the previous icons used: 4 bytes per pixel in
B, G, R, A order, non-premultiplied. At 68x68 that is 18,496 bytes of pixel
data per icon in flash.

Artwork: Meteocons v3 (https://meteocons.com/) by Bas Milius, MIT licensed.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
IMG_DIR = os.path.join(PROJECT, "src", "img")
CACHE = os.path.join(HERE, ".meteocons-cache")

SVG_URL = ("https://raw.githubusercontent.com/basmilius/weather-icons/dev/"
           "production/{style}/{variant}/{name}.svg")

# Meteocons only ships monochrome as static; fill and line have both trees.
VARIANTS = {"fill": ("svg", "svg-static"), "line": ("svg", "svg-static"),
            "monochrome": ("svg-static",)}

# firmware symbol            WMO code(s)          Meteocons icon
MAPPING = [
    ("Clear_sky",                     "0",       "clear-day"),
    ("Mainly_clear",                  "1",       "partly-cloudy-day"),
    ("Partly_cloudy",                 "2",       "cloudy"),
    ("Overcast",                      "3",       "overcast"),
    ("Fog",                           "45",      "fog"),
    ("Depositing_rime_fog",           "48",      "mist"),
    ("Light_drizzle",                 "51",      "drizzle"),
    ("Moderate_drizzle",              "53",      "partly-cloudy-day-drizzle"),
    ("Dense_drizzle",                 "55",      "overcast-drizzle"),
    ("Slight_rain",                   "61",      "rain"),
    ("Moderate_rain",                 "63",      "overcast-rain"),
    ("Heavy_rain",                    "65",      "extreme-rain"),
    ("Slight_snow_fall",              "71",      "snow"),
    ("Moderate_snow_fall",            "73",      "overcast-snow"),
    ("Heavy_snow_fall",               "75",      "extreme-snow"),
    ("Slight_rain_showers",           "80",      "partly-cloudy-day-rain"),
    ("Moderate_rain_showers",         "81",      "overcast-day-rain"),
    ("Violent_rain_showers",          "82",      "extreme-rain"),
    ("Thunderstorm",                  "95",      "thunderstorms"),
    ("Thunderstorm_with_slight_hail", "96",      "thunderstorms-rain"),
    ("Thunderstorm_with_heavy_hail",  "99",      "thunderstorms-extreme-rain"),
    ("Unknown",                       "default", "not-available"),
]

HEADER = """\
/* {symbol} - weather icon for WMO code {code}.
 *
 * Generated by tools/make-weather-icons.py - do not edit by hand.
 * Artwork: Meteocons v3 (https://meteocons.com/) by Bas Milius.
 * Source:  {url}
 * Converted to a {w}x{h} LVGL 9 ARGB8888 image descriptor (style: {style}).
 *
 * MIT License
 *
 * Copyright (c) 2020-2024 Bas Milius
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#ifdef __has_include
    #if __has_include("lvgl.h")
        #ifndef LV_LVGL_H_INCLUDE_SIMPLE
            #define LV_LVGL_H_INCLUDE_SIMPLE
        #endif
    #endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
    #include "lvgl.h"
#else
    #include "lvgl/lvgl.h"
#endif


#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMAGE_{symbol_upper}
#define LV_ATTRIBUTE_IMAGE_{symbol_upper}
#endif
"""


def fetch(name: str, style: str) -> str:
    """Return the SVG source for `name`, downloading it into the cache once."""
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, f"{style}--{name}.svg")
    if os.path.exists(path) and os.path.getsize(path) > 0:
        return open(path, encoding="utf-8").read()
    last = None
    for variant in VARIANTS[style]:
        url = SVG_URL.format(style=style, variant=variant, name=name)
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "make-weather-icons"})
            data = urllib.request.urlopen(req, timeout=30).read().decode("utf-8")
        except Exception as exc:                      # noqa: BLE001 - report and try next
            last = f"{url}: {exc}"
            continue
        open(path, "w", encoding="utf-8").write(data)
        return data
    raise SystemExit(f"could not download {name!r} ({style}): {last}")


def rasterise(svg_path: str, size: int) -> bytes:
    """SVG -> raw RGBA bytes at size x size, via rsvg-convert."""
    out = svg_path + ".png"
    subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(size),
                    "-o", out, svg_path], check=True)
    # Pillow is only needed here, and is present in the dev environment.
    from PIL import Image
    im = Image.open(out).convert("RGBA")
    assert im.size == (size, size), f"{svg_path}: got {im.size}"
    return im.tobytes()


def emit(symbol: str, code: str, name: str, style: str, size: int,
         rgba: bytes, url: str) -> str:
    """Build the .c file text: LVGL wants B,G,R,A order (non-premultiplied)."""
    assert len(rgba) == size * size * 4
    bgra = bytearray(len(rgba))
    bgra[0::4] = rgba[2::4]      # B
    bgra[1::4] = rgba[1::4]      # G
    bgra[2::4] = rgba[0::4]      # R
    bgra[3::4] = rgba[3::4]      # A

    head = HEADER.format(symbol=symbol, symbol_upper=symbol.upper(), code=code,
                         style=style, w=size, h=size, url=url)
    lines = [head,
             f"const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST "
             f"LV_ATTRIBUTE_IMAGE_{symbol.upper()} uint8_t {symbol}_map[] = {{"]
    for i in range(0, len(bgra), 16):
        lines.append("  " + " ".join(f"0x{b:02x}," for b in bgra[i:i + 16]))
    lines.append("};")
    lines.append("")
    lines.append(f"const lv_image_dsc_t {symbol} = {{")
    lines.append("  .header.cf = LV_COLOR_FORMAT_ARGB8888,")
    lines.append("  .header.magic = LV_IMAGE_HEADER_MAGIC,")
    lines.append(f"  .header.w = {size},")
    lines.append(f"  .header.h = {size},")
    lines.append(f"  .data_size = {size * size} * 4,")
    lines.append(f"  .data = {symbol}_map,")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--style", default="fill", choices=sorted(VARIANTS))
    ap.add_argument("--size", type=int, default=68)
    ap.add_argument("--out", default=IMG_DIR)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    total = len(MAPPING) * args.size * args.size * 4
    print(f"style={args.style} size={args.size} icons={len(MAPPING)} "
          f"-> {total / 1024:.0f} KB of pixel data")
    print(f"output: {args.out}\n")

    for symbol, code, name in MAPPING:
        url = SVG_URL.format(style=args.style, variant=VARIANTS[args.style][-1], name=name)
        svg = fetch(name, args.style)
        tmp = os.path.join(CACHE, f"{args.style}--{name}.svg")
        rgba = rasterise(tmp, args.size)
        text = emit(symbol, code, name, args.style, args.size, rgba, url)
        dest = os.path.join(args.out, f"{symbol}.c")
        old = os.path.getsize(dest) if os.path.exists(dest) else 0
        if not args.dry_run:
            os.makedirs(args.out, exist_ok=True)
            with open(dest, "w", encoding="utf-8") as fh:
                fh.write(text)
        print(f"  {symbol:32} <= {name:28} {len(text):7,} B  (was {old:,} B)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
